name: dartdb
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

dependencies:
  args: ^2.4.0
  path: ^1.9.0
  pretty_print_json: ^1.0.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  stream_transform: ^2.1.0
  uuid: ^4.4.2
  vm_service: ^14.2.4
  watcher: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  hotreloader:
  test: ^1.24.0
